config/routes.rb
Jade::Application.routes.draw do
  resources :certificates

  get 'index' => "pages#index"
  get 'about' => "pages#about"
  get 'password' => "password#new"
  post 'update_password' => "password#udpate"
  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  get 'logout' => "sessions#destroy"
  
  resources :users

  root to: 'pages#index'

end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
  def new
  end

  def udpate
  	user_email = User.find(session[:user_id]).email
  	if user = User.authenticate(user_email, params[:password_current])
  		if params[:password_new] == params[:password_new_confirmation]
  			user.password = params[:password_new]
  			if user.save
  				session[:user_id] = nil
  				redirect_to login_path, notice: "Your password update successfully, please login again."
  			else
  				redirect_to password_path, alert: "something wrong happend, please try again."
  			end
  		else
  			redirect_to password_path, alert: "Verify password is not equal to new password!"
  		end
  	else
  		redirect_to password_path, alert: "Your current password is wrong!"
  	end
  end
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/views/password/new.html.erb
<h1>更改密码</h1>

<%= form_tag update_password_path, class: "form-horizontal" do  %>

  <div class="form-group">
    <%= label_tag 'password_current', '当前密码：', class: "control-label col-sm-2" %>
    <div class="col-sm-4">
    	<%= password_field_tag :password_current, params[:password_current], class: "form-control", placeholder: "输入当前密码", required: true, autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag 'password_new', '新密码：', class: "control-label col-sm-2" %>
    <div class="col-sm-4">
    	<%= password_field_tag :password_new, params[:password_new], class: "form-control", placeholder: "新密码", required: true %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag 'password_new_confirmation', '确认新密码：', class: "control-label col-sm-2" %>
    <div class="col-sm-4">
    	<%= password_field_tag :password_new_confirmation, params[:password_new_confirmation], class: "form-control", placeholder: "确认新密码", required: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= submit_tag '确认', class: "btn btn-success" %> <%= link_to '返回', root_path, class: "btn btn-link" %>
    </div>
  </div>

<% end %>