config/routes.rb
Jade::Application.routes.draw do
  resources :certificates

  get 'index' => "pages#index"
  get 'about' => "pages#about"
  get 'password' => "password#new"
  post 'update_password' => "password#udpate"
  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  get 'logout' => "sessions#destroy"
  
  resources :users

  root to: 'pages#index'

end

app/models/certificate.rb
class Certificate < ActiveRecord::Base

	mount_uploader :img_url, ImgUrlUploader

	SHAPE = %w{旦形 佛公 马鞍面 怀古/圆扣 梨形 观音 长方形 筒珠/蘭豆 心/杏心形 圆形 方形 圆珠/圆环 榄尖形 花件 十字架 首饰套装/摆件}
	OBJECT = %w{戒指 吊坠 耳环 襟针 手链 颈链 袖扣 手镯}
	CUT = %w{卜面 平面 拱面}
	MEASURE = %w{测量 未能测量}
	TRANSPARENCY = %w{半透明 全透明 不透明 未能测量}
	POLARISCOPE = %w{多晶质 各向异性 各向同性 异常消光 未能测量}
	DEEP1 = %w{淡 浅 绿 鲜 浓 深 暗}
	COLOR1 = %w{绿色 黄绿色 蓝绿色}
	DEEP2 = %w{淡 浅 绿 鲜 浓 深 暗}
	COLOR2 = %w{绿色 黄绿色 蓝绿色}
	DEEP3 = %w{淡 浅 绿 鲜 浓 深 暗}
	COLOR3 = %w{绿色 黄绿色 蓝绿色}
	DISTRIBUTION = %w{均匀 不均匀 塊状 脈状 点状}
	MAGNIFICATION = %w{粒状及纤维状晶体结构（中粒） 纤维状晶体结构（幼粒） 粒状晶体结构（粗粒）}
	SURFACE_FEATURE = %w{铁渗 翠性 小坑洞 橙皮纹 微小裂纹 沟漕}
	INFRARED_SPECTRUM = %w{不含树脂物质 含树脂物质}

	belongs_to :user

	after_initialize :date_for_issue

	before_save :weight_round_down_3, :val_sg

	#当新建证书或者修改证书的时候，证书的签发日期默认就等于测试日期
	def date_for_issue
    self.date_issue = date_test
  end

  # round down 3位小数
  def weight_round_down_3
    self.weight = weight.to_f < 1 ? weight.to_i.to_f : (weight - 0.5 / 10**3).round(3)
  end

  # 求sg的值
  def val_sg
  	self.sg = ((ww1.to_f + ww2.to_f + ww3.to_f)/3).round(2)
  end

end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  FONTS_PATH = "public/assets/fonts/"

  before_action :set_certificate, only: [:show, :edit, :update, :destroy]

  # GET /certificates
  # GET /certificates.json
  def index
    @certificates = Certificate.all
  end

  # GET /certificates/1
  # GET /certificates/1.json
  def show
    # if no pdf folder, here will auto create the pdf folder
    unless Dir.exist?("pdf")
      Dir.mkdir("pdf")
    end

    @file_name = "#{User.find_by_id(session[:user_id]).ename}.pdf"
    @pdf_file = "pdf/" + @file_name

    # require "prawn/measurement_extensions"

    Prawn::Document.generate(
      @pdf_file,
      left_margin: 40,
      :page_size => 'A4') do |pdf|

      pdf.font_families["msyh"] = {
        normal: {file: "#{FONTS_PATH}/msyh.ttf"},
        bold: {file: "#{FONTS_PATH}/msyhbd.ttf"}
      }

      pdf.font("msyh", size: 7) do

        # pdf.stroke_axis :step_length => 20

        pdf.bounding_box([10, 770], :width => 200, :height => 90, :padding => 20) do
          pdf.image "#{Rails.root}/app/assets/images/pdf_header.jpg", :width => 200, :height => 90
        end

        pdf.move_cursor_to 670

        pdf.text "翡翠鉴定报告  Fei Cui Testing Report",size: 16,:style => :bold

        pdf.move_cursor_to 650

        data1 = [
          ["报告号码 Report No.", ":", {:content => "#{@certificate.report_no}", :colspan => 5, :align => :center}],
          ["测试日期 Test Date", ":", "#{@certificate.date_test}", "","签发日期 Issue Date", ":", "#{@certificate.date_issue}"]]

        pdf.table(data1, :position => :right) do
          cells.border_width = 0
          row(0).columns(2).borders = [:bottom]
          row(0).columns(2).border_width = 1
          row(1).columns([2,6]).borders = [:bottom]
          row(1).columns([2,6]).border_width = 1
        end

        pdf.move_cursor_to 630

        pdf.text "鉴定结果  Test Result",size: 14

        pdf.move_cursor_to 600

        @weight = @certificate.weight < 200 ? @certificate.weight.round(2) : @certificate.weight
        @dimension =  (@certificate.dimensions1 && @certificate.dimensions2 && @certificate.dimensions3) ? "约/Appro. #{@certificate.dimensions1}x #{@certificate.dimensions2}x #{@certificate.dimensions3}" : "约/Appro. #{@certificate.dimensions1}x #{@certificate.dimensions2}" 

        data2 = [
          ["形状和琢型", "Shape and Cut", ":", "#{@certificate.shape}#{@certificate.object} - #{@certificate.cut}"],
          ["", "", "", "Bunddha Pendant"],
          ["尺寸（毫米）", "Dimensions(mm)", ":", "#{@dimension}"],
          ["重量（克拉）", "Weight(ct)", ":", "#{@weight} （#{@certificate.weight_desc} With Mounting）"],
          ["透明度", "Transparency", ":", "#{@certificate.transparency} Transparency"],
          ["颜色", "Color", ":", "#{@certificate.color1}"],
          ["", "", "", "Pale Green"],
          ["偏光仪", "Polariscope", ":", "#{@certificate.polariscope} Polycrystalline"],
          ["折射率", "Refractive Index", ":", "#{@certificate.refractive_index}"],
          ["比重", "Specific Gravity", ":", "#{@certificate.is_measure} Not Measurable"],
          ["荧光", "Fluorescence", "", ""],
          ["紫外线长波", "UV-LW", ":", "#{@certificate.uv_lw} Faint"],
          ["紫外线短波", "UV-SW", ":", "#{@certificate.uv_sw} Faint"],
          ["滤色镜", "Chelsea Color Filter", ":", "#{@certificate.chelsea_color_filter} Green"],
          ["可见光谱", "Visible Spectrum", ":", "#{@certificate.visible_spectrum}"],
          ["", "", "", "Fei Cui Spectrum"],
          ["放大观察", "Magnification", ":", "#{@certificate.magnification} - #{@certificate.surface_feature}"],
          ["", "", "", "Fine Granular & Fibrous Texture"]]

        pdf.table(data2) do
          cells.border_width = 0
          row(0..9).columns(3).borders = [:bottom]
          row(0..9).columns(3).border_width = 1
          row(11..18).columns(3).borders = [:bottom]
          row(11..18).columns(3).border_width = 1
        end

        pdf.move_cursor_to 600

        data3 = [
          ["应用仪器", "Instruments Used"],
          ["滤色镜", "Chelsea Color Filter"],
          ["电子磅", "Electonic Balance"],
          ["电子表尺", "Electronic Gauge"],
          ["电子卡尺", "Electronic Caliper"],
          ["红外线光谱仪", "FTIR Spectrometer"],
          ["宝石学显微镜", "Gemmological Microscope"],
          ["偏光仪", "Polariscope"],
          ["折射仪", "Refractometer"],
          ["分光仪", "Spectroscope"],
          ["荧光灯", "Ultra-violet Lamp"],
          [{:content => "彩色照片只显示测试石的形状\nColor photo shows the shape of test stone only", :colspan => 2}],
          [{:content => "箭咀所示为测试物\nOnly arrow pointed stone is being tested", :colspan => 2}]]

        pdf.table(data3, :position => :right, :width => 200) do
          cells.border_width = 0
          cells.padding = 0
          row(0).padding_bottom = 5
          row(1..10).padding_left = 2
          row(11..12).padding_top = 5
          row(1..10).size = 6
          row(0..3).columns(2).borders = [:bottom]
          row(0..3).columns(2).border_width = 1
        end

        pdf.move_cursor_to 270

        pdf.image "public/#{@certificate.img_url}", :height => 160 if @certificate.img_url.present?

        pdf.move_cursor_to 210

        data4 = [
          ["结论", ":", "#{@certificate.conclusion} - #{@certificate.level}玉"],
          ["Conclusion", ":", "Natural Fei Cui - Type A"],
          ["评论", ":", "#{@certificate.comments}"],
          ["Comments", ":", "Natural Color Fei Cui without resin"]]

        pdf.table(data4, :position => :right) do
          cells.border_width = 0
          row(0..3).columns(2).borders = [:bottom]
          row(0..3).columns(2).border_width = 1
        end

        pdf.move_cursor_to 90

        data5 = [
          ["红外线光谱", "Infrared Spectrum", ":", "#{@certificate.infrared_spectrum}"],
          ["", "", ":", "No resin is detected"]]

        pdf.table(data5) do
          cells.border_width = 0
          row(0..1).columns(3).borders = [:bottom]
          row(0..1).columns(3).border_width = 1
        end

        pdf.move_cursor_to 70

        data6 = [
          ["", ""],
          ["#{@certificate.user.cname}", "#{@certificate.user.ename}"],
          ["#{@certificate.user.ctitle}", "#{@certificate.user.etitle}"]]

        pdf.table(data6, :position => :right, :width => 180) do
          cells.border_width = 0
          row(0).borders = [:bottom]
          row(0).border_width = 1
        end

        pdf.move_cursor_to 20

        pdf.text "END OF REPORT (P1 OF 1)", :align => :center

      end

    end
    send_file(@pdf_file,
              filename: "#{@certificate.report_no}.pdf",
              type: "application/pdf",
              disposition: "inline")
  end

  # GET /certificates/new
  def new
    @certificate = Certificate.new
  end
  # GET /certificates/1/edit
  def edit
  end

  # POST /certificates
  # POST /certificates.json
  def create
    @certificate = Certificate.new(certificate_params)

    respond_to do |format|
      if @certificate.save
        format.html { redirect_to certificates_path, notice: '证书创建成功' }
        format.json { render action: 'index', status: :created, location: @certificate }
      else
        format.html { render action: 'new' }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certificates/1
  # PATCH/PUT /certificates/1.json
  def update
    respond_to do |format|
      if @certificate.update(certificate_params)
        format.html { redirect_to certificates_path, notice: '证书修改成功' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certificates/1
  # DELETE /certificates/1.json
  def destroy
    @certificate.destroy
    respond_to do |format|
      format.html { redirect_to certificates_url, notice: "删除 #{@certificate.report_no} 证书成功" }
      format.json { head :no_content }
    end
    Dir.rmdir("public/uploads/certificate/img_url/#{@certificate.id}") if Dir.exist?("public/uploads/certificate/img_url/#{@certificate.id}")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certificate
      @certificate = Certificate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certificate_params
      params.require(:certificate).permit(:report_no, :is_hoklas, :date_test, :date_issue, :shape, :object, :cut, :dimensions1, :dimensions2, :dimensions3, :dimension, :weight, :weight_desc, :transparency, :deep1, :color1, :deep2, :color2, :deep3, :color3, :distribution, :polariscope, :refractive_index, :is_measure, :ww1, :ww2, :ww3, :sg, :uv_lw, :uv_sw, :chelsea_color_filter, :visible_spectrum, :magnification, :surface_feature, :infrared_spectrum, :level, :conclusion, :comments, :img_url, :user_id)
    end
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/views/certificates/_form.html.erb
<%= form_for(@certificate) do |f| %>

  <div class="item-group">
    <div class="item">
      <%= f.label :report_no, '证书编号：' %>
      <%= f.text_field :report_no, size: 16 %>
    </div>
    
  </div>
  <div class="item-group">
    <div class="item">
      <%= f.label :date_test, '测试/签发日期：' %>
      <%= f.date_select :date_test %>
    </div>
  </div>

  <div class="item-group">
    <div class="item">
      <%= f.radio_button :is_hoklas, '翡翠鉴定报告' %>
      <%= f.label :is_hoklas_a, '翡翠鉴定报告' %>
      <%= f.radio_button :is_hoklas, '翡翠鉴定证书', checked: 'checked' %>
      <%= f.label :is_hoklas_b, '翡翠鉴定证书' %>
    </div>
  </div>

  <div class="item-group">
    <label for="">形状及车工：</label>
    <div class="item">
      <%= f.label :shape, '形状：' %>
      <%= f.select :shape, Certificate::SHAPE %>
      <%= f.select :object, Certificate::OBJECT %>
    </div>
    <div class="item">
      <%= f.label :cut, '车工：' %>
      <%= f.select :cut, Certificate::CUT %>
    </div>
  </div>

  <div class="item-group">
    <div class="item">
      <%= f.label :dimensions1, '尺寸一：' %>
      <%= f.text_field :dimensions1, size: 6, required: true %>
      <%= f.label :dimensions2, '尺寸二：' %>
      <%= f.text_field :dimensions2, size: 6, required: true %>
      <%= f.label :dimensions3, '尺寸三：' %>
      <%= f.text_field :dimensions3, size: 6 %>
    </div>
  </div>

  <div class="item-group">
    <div class="item">
      <%= f.label :weight, '重量：' %>
      <%= f.text_field :weight, size: 8 %>
      <%= f.radio_button :weight_desc, "裸石", checked: 'checked' %>
      <%= f.label :weight_desc_a, '裸石' %>
      <%= f.radio_button :weight_desc, "整件饰物" %>
      <%= f.label :weight_desc_b, '整件饰物' %>
      <%= f.radio_button :weight_desc, "整件饰物" %>
      <%= f.label :weight_desc_c, '整件饰物-连绳' %>
    </div>
  </div>

  <div class="item-group">
    <div class="item">
      <%= f.label :is_measure, '比重值：' %>
      <%= f.select :is_measure, Certificate::MEASURE %>
    </div>
    <div class="item weight">
      <%= f.label :ww1, 'ww1：' %>
      <%= f.text_field :ww1, size: 8 %>
      <%= f.label :ww2, 'ww2：' %>
      <%= f.text_field :ww2, size: 8 %>
      <%= f.label :ww3, 'ww3：' %>
      <%= f.text_field :ww3, size: 8 %>
      <%= f.label :sg, 'SG值：' %>
      <%= f.text_field :sg, size: 8, disabled: "disabled" %>
    </div>
  </div>

  <div class="item-group">
    <div class="item">
      <%= f.label :transparency, '透明度：' %>
      <%= f.select :transparency, Certificate::TRANSPARENCY %>
    </div>
    <div class="item">
      <%= f.label :polariscope, '偏光仪：' %>
      <%= f.select :polariscope, Certificate::POLARISCOPE %>
    </div>
    <div class="item">
      <%= f.label :refractive_index, '折射率：' %>
      <%= f.text_field :refractive_index, size: 6 %>
    </div>
  </div>
  
  <div class="item-group">
    <label for="">颜色深浅度：</label>
    <div class="item">
      <%= f.label :deep1, '深浅度一：' %>
      <%= f.select :deep1, Certificate::DEEP1 %>
      <%= f.label :color1, '颜色一：' %>
      <%= f.select :color1, Certificate::COLOR1 %>
      <%= f.label :deep2, '深浅度二：' %>
      <%= f.select :deep2, Certificate::DEEP2 %>
      <%= f.label :color2, '颜色二：' %>
      <%= f.select :color2, Certificate::COLOR2 %>
      <%= f.label :deep3, '深浅度三：' %>
      <%= f.select :deep3, Certificate::DEEP3 %>
      <%= f.label :color3, '颜色三：' %>
      <%= f.select :color3, Certificate::COLOR3 %>
    </div>
    <div class="item">
      <%= f.label :distribution, '分布：' %>
      <%= f.select :distribution, Certificate::DISTRIBUTION %>
    </div>
  </div>

  <div class="item-group">
    <label for="">荧光效应：</label>
    <div class="item">
      <%= f.label :uv_lw, '荧光线长波：' %>
      <%= f.radio_button :uv_lw, "无", checked: 'checked' %>
      <%= f.label :uv_lw_a, '无' %>
      <%= f.radio_button :uv_lw, "弱" %>
      <%= f.label :uv_lw_b, '弱' %>
      <%= f.radio_button :uv_lw, "中" %>
      <%= f.label :uv_lw_c, '中' %>
      <%= f.radio_button :uv_lw, "强" %>
      <%= f.label :uv_lw_d, '强' %>
    </div>
    <div class="item">
      <%= f.label :uv_sw, '荧光线短波：' %>
      <%= f.radio_button :uv_sw, "无", checked: 'checked' %>
      <%= f.label :uv_sw_a, '无' %>
      <%= f.radio_button :uv_sw, "弱" %>
      <%= f.label :uv_sw_b, '弱' %>
      <%= f.radio_button :uv_sw, "中" %>
      <%= f.label :uv_sw_c, '中' %>
      <%= f.radio_button :uv_sw, "强" %>
      <%= f.label :uv_sw_d, '强' %>
    </div>
  </div>
  
  <div class="item-group">
    <%= f.label :chelsea_color_filter, '滤色镜：' %>
    <%= f.radio_button :chelsea_color_filter, "绿色" %>
    <%= f.label :chelsea_color_filter_a, '绿色' %>
    <%= f.radio_button :chelsea_color_filter, "红色" %>
    <%= f.label :chelsea_color_filter_b, '红色' %>
    <%= f.radio_button :chelsea_color_filter, "颜色不变" %>
    <%= f.label :chelsea_color_filter_c, '颜色不变' %>
  </div>
  <div class="item-group">
    <%= f.label :visible_spectrum, '可见光谱：' %>
    <%= f.radio_button :visible_spectrum, "硬玉光谱", checked: 'checked' %>
    <%= f.label :visible_spectrum_a, '硬玉光谱' %>
    <%= f.radio_button :visible_spectrum, "染色光谱" %>
    <%= f.label :visible_spectrum_b, '染色光谱' %>
  </div>
  <div class="item-group">
    <label for="">放大观察（表面特征）：</label>
      <%= f.select :magnification, Certificate::MAGNIFICATION %>
      <%= f.select :surface_feature, Certificate::SURFACE_FEATURE %>
  </div>

  <div class="item-group">
    <div class="item">
      <%= f.label :level, '翡翠级别：' %>
      <%= f.radio_button :level, "A", checked: 'checked' %>
      <%= f.label :level_a, 'A' %>
      <%= f.radio_button :level, "B" %>
      <%= f.label :level_b, 'B' %>
      <%= f.radio_button :level, "C" %>
      <%= f.label :level_c, 'C' %>
      <%= f.radio_button :level, "BC" %>
      <%= f.label :level_bc, 'B+C' %>
    </div>
  </div>

  <div class="item-group">
    <div class="item">
      <%= f.label :infrared_spectrum, '红外线光谱：' %>
      <%= f.select :infrared_spectrum, Certificate::INFRARED_SPECTRUM %>
    </div>
  </div>

  <div class="item-group">
    <div class="item">
      <%= f.label :conclusion, '结论：' %>
      <%= f.radio_button :conclusion, "天然颜色翡翠" %>
      <%= f.label :conclusion_a, '天然颜色翡翠' %>
      <%= f.radio_button :conclusion, "处理翡翠树脂充填" %>
      <%= f.label :conclusion_b, '处理翡翠树脂充填' %>
      <%= f.radio_button :conclusion, "处理翡翠颜料染色" %>
      <%= f.label :conclusion_c, '处理翡翠颜料染色' %>
    </div>
  </div>

  <div class="item-group">
    <%= f.label :img_url, '选择图片：', class: "item" %>
    <%= f.file_field :img_url, accept: 'image/png,image/gif,image/jpeg,image/jpg', class: "item" %>
  </div>
  <div class="item-group">
    <%= f.label :comments, '评论：' %>
    <%= f.text_area :comments, rows: 5, cols: 40 %>
  </div>
  <div class="item-group">
    <%= f.label :user_id, '鉴证师：' %>
    <%= f.collection_select :user_id, User.all, :id, :ename, prompt: "请选择用户", selected: @certificate.user_id || session[:user_id] %>
  </div>
  <div class="actions">
    <%= f.submit '确认', class: "btn btn-success" %>&nbsp;&nbsp;<%= link_to '返回', certificates_path %>
  </div>
<% end %>

<script type="text/javascript">

  $(function() {

    // 折射率默认为1.66
    $refractive_index = $('#certificate_refractive_index');
    if ($refractive_index.val() == "") {
      $refractive_index.val(1.66);
    };

    // SG值默认为(WW1+WW2+WW3)/3，再四舍五入，保留2位小数
    $("input[id^=certificate_ww]").change(function(event) {
      val_sg = Math.round((($("#certificate_ww1").val() * 1 + $("#certificate_ww2").val() * 1 + $("#certificate_ww3").val() * 1)/3)*100)/100;
      $("#certificate_sg").val(val_sg);
    });

    if ($("#certificate_is_measure").val() == '未能测量') {
      $(".weight").hide();
    }

    // 当裸石时，比重值自动选择“测量”
    $("#certificate_weight_desc_a").change(function(event) {
      $("#certificate_is_measure").val('测量');
      $(".weight").show();
     });

    // 当比重值为“未能测量”时，WW1、WW2和WW3不能输入
    $("#certificate_is_measure").change(function(event) {
      if ($("#certificate_is_measure").val() == "未能测量") {
        $("#certificate_ww1").val('');
        $("#certificate_ww2").val('');
        $("#certificate_ww3").val('');
        $("#certificate_sg").val('');
        $(".weight").hide();
      } else if ($("#certificate_is_measure").val() == "测量") {
        $(".weight").show();
      }
    });

    // 如果翡翠级别为A或C，红外线光谱自动选择“不含树脂物质”，否则自动选择“含树脂物质”
    $("input[id^=certificate_level_]").change(function(event) {
      if ($(this).attr('id') == 'certificate_level_a' || $(this).attr('id') == 'certificate_level_c') {
        $("#certificate_infrared_spectrum").val("不含树脂物质");
      } else {
        $("#certificate_infrared_spectrum").val("含树脂物质");
      }
    });

    //如果“透明度”或“比重值”或“偏光仪”其中一项选择了“未能测量”，program自动选择为"report"，否则选择"certificate"
    $("#certificate_is_measure").change(function(event) {
      if ($("#certificate_is_measure").val() != "未能测量" && $("#certificate_transparency").val() != "未能测量" && $("#certificate_polariscope").val() != "未能测量") {
        $("#certificate_is_hoklas_b").prop('checked', 'checked');
      } else {
        $("#certificate_is_hoklas_a").prop('checked', 'checked');
      }
    });
    $("#certificate_transparency").change(function(event) {
      if ($("#certificate_is_measure").val() != "未能测量" && $("#certificate_transparency").val() != "未能测量" && $("#certificate_polariscope").val() != "未能测量") {
        $("#certificate_is_hoklas_b").prop('checked', 'checked');
      } else {
        $("#certificate_is_hoklas_a").prop('checked', 'checked');
      }
    });
    $("#certificate_polariscope").change(function(event) {
      if ($("#certificate_is_measure").val() != "未能测量" && $("#certificate_transparency").val() != "未能测量" && $("#certificate_polariscope").val() != "未能测量") {
        $("#certificate_is_hoklas_b").prop('checked', 'checked');
      } else {
        $("#certificate_is_hoklas_a").prop('checked', 'checked');
      }
    });

    $("#certificate_is_hoklas_a").change(function(event) {
      if ($("#certificate_is_measure").val() != "未能测量" && $("#certificate_transparency").val() != "未能测量" && $("#certificate_polariscope").val() != "未能测量") {
        alert("“透明度”或“比重值”或“偏光仪”其中一项必须选择为“未能测量”");
        $("#certificate_is_hoklas_b").prop('checked', 'checked');
      }
    });
    $("#certificate_is_hoklas_b").change(function(event) {
      if ($("#certificate_is_measure").val() == "未能测量" || $("#certificate_transparency").val() == "未能测量" || $("#certificate_polariscope").val() == "未能测量") {
        alert("“透明度”或“比重值”或“偏光仪”其中一项已选择为“未能测量”，不能选择为“翡翠鉴定证书”");
        $("#certificate_is_hoklas_a").prop('checked', 'checked');
      }
    });


  });

</script>

app/views/certificates/edit.html.erb
<h1>修改证书</h1>

<%= render 'form' %>

app/views/certificates/index.html.erb
<h1>证书列表</h1>

<div class="table-responsive">
  <table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th>编号</th>
        <th>测试日期</th>
        <th>签发日期</th>
        <th>鉴定师</th>
        <th>动作</th>
      </tr>
    </thead>

    <tbody>
      <% @certificates.each do |certificate| %>
        <tr>
          <td><%= certificate.report_no %></td>
          <td><%= certificate.date_test %></td>
          <td><%= certificate.date_issue %></td>
          <td><%= certificate.user.ename %></td>
          <td>
            <%= link_to ' 查看', certificate, class: "btn btn-info btn-xs fa fa-eye", target: "_blank" %>
            <%= link_to ' 编辑', edit_certificate_path(certificate), class: "btn btn-warning btn-xs fa fa-pencil" %>
            <%= link_to ' 删除', certificate, method: :delete, data: { confirm: "您真的想删除 #{certificate.report_no} 吗？" }, class: "btn btn-danger btn-xs fa fa-trash-o" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to ' 新建证书', new_certificate_path, class: "btn btn-success btn-sm fa fa-file" %>

app/views/certificates/new.html.erb
<h1>新建证书</h1>

<%= render 'form' %>