config/routes.rb
Jade::Application.routes.draw do
  resources :certificates

  get 'index' => "pages#index"
  get 'about' => "pages#about"
  get 'password' => "password#new"
  post 'update_password' => "password#udpate"
  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  get 'logout' => "sessions#destroy"
  
  resources :users

  root to: 'pages#index'

end

app/views/layouts/_footer.html.erb
<div class="pull-left">
	<p>
		<i class="fa fa-flag"></i> 当前的版本是： <a href="https://github.com/vincentjiang/jade/" target="_blank">V1.0</a>
	</p>
</div>
<div class="pull-right">
	<p>
		对使用系统有任何疑问? 请联系 <a class="btn btn-xs btn-info" href="">IT部 <i class="fa fa-envelope"></i></a>
	</p>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Twitter Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to ' 首页', root_path, class: 'navbar-brand fa fa-home' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-left">
        <%= render 'layouts/navigation_left_links' %>
      </ul>
      <div class="navbar-right">
        <%= render 'layouts/navigation_right_links' %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_left_links.html.erb
<%# add navigation right links to this file %>
<% if session[:user_id] %>

	<li>
		<a href="<%= certificates_path %>">
			<i class="fa fa-file"></i> 证书管理
		</a>
	</li>

	<% if User.find(session[:user_id]).role == "管理员" %>
		<li>
			<a href="<%= users_path %>">
				<i class="fa fa-user"></i> 用户管理
			</a>
		</li>
	<% end %>

<% end %>

<li>
	<a href="<%= about_path %>"><i class="fa fa-info-circle"></i> 关于</a>
</li>

app/views/layouts/_navigation_right_links.html.erb
<%# add navigation right links to this file %>

<% if session[:user_id] %>
	<ul class="nav navbar-nav">
		<li><a href="<%= user_path(session[:user_id]) %>" data-toggle="tooltip" data-placement="bottom" data-original-title="<%= User.find(session[:user_id]).ename %>"><i class="fa fa-user"></i></a></li>
		<li><a href="<%= password_path %>" data-toggle="tooltip" data-placement="bottom" data-original-title="更改密码"><i class="fa fa-key"></i></a></li>
		<li><a href="<%= logout_path %>" data-toggle="tooltip" data-placement="bottom" data-original-title="退出系统" onCLick="return confirm('您真的想退出系统吗？')"><i class="fa fa-sign-out"></i></a></li>
	</ul>
<% else %>
	<a class="btn btn-success navbar-btn" href="<%= login_path %>">登录 <i class="fa fa-sign-in"></i></a>
<% end %>

<script type="text/javascript">

	$('a[data-original-title]').hover(function(){
		$(this).tooltip('show');
	});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="shortcut icon" href="http://vincentjiang.u.qiniudn.com/ruby.png" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Jade" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Jade" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body style="background-color: #eee;">

    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <main role="main">
      <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </main>

    <div class="container">
      <footer>
        <%= render 'layouts/footer' %>
      </footer>
    </div>
  </body>
</html>